name: PR to Markdown

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  convert-pr:
    runs-on: ubuntu-latest
    
    # Este important să oferi permisiuni de scriere dacă acțiunea face commit automat
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PR to MD action
        uses: ryohidaka/action-pr-to-md@main
        # Aici poți adăuga parametri suplimentari dacă acțiunea îi cere (verifică secțiunea "inputs" din action.yml)
        # with:
        #   param_nume: valoare
