name: PR to Markdown

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  convert-pr:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PR to MD action
        uses: ryohidaka/action-pr-to-md@main
        with:
          user_name: 'catalin87' # Pune username-ul tău de GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
