name: PR to Markdown

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:

jobs:
  convert-pr:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PR to MD action
        uses: ryohidaka/action-pr-to-md@main
        with:
          user_name: 'catalin87'
          output_file_path: 'output.md'
          states: 'open, merged, closed'
          since: '2024-01-01' # Pune o dată de la care ai început să ai PR-uri
          included_repos: 'YOURLS' # Opțional: Forțează să caute doar în acest repo pentru test
